### ISSUE TITLE
Install instructions for ARDroneLib don't work as expected

### ISSUE THREAD

**Issue by lr-morales** [JdeRobot/ThirdParty#7]
The README.md states that to build ARDroneLib you only need to get the CMakeLists file and run cmake over it. As soon as you reach this step, CMake reports missing files from the repo to continue. 
An execution example could be this (CMakeLists download step ommited in the example, assumes that the file is already downloaded::

```
# cmake .
 -- The C compiler identification is GNU 4.9.2`
 -- The CXX compiler identification is GNU 4.9.2
 -- Check for working C compiler: /usr/bin/cc
 -- Check for working C compiler: /usr/bin/cc -- works
 -- Detecting C compiler ABI info
 -- Detecting C compiler ABI info - done
 -- Check for working CXX compiler: /usr/bin/c++
 -- Check for working CXX compiler: /usr/bin/c++ -- works
 -- Detecting CXX compiler ABI info
 -- Detecting CXX compiler ABI info - done
 ardronelib version: autonomy-gps
 -- Found Git: /usr/bin/git (found version "2.1.4")
 CMake Error: File /root/ardronelib-build/ffmpeg-0.8.pc.in does not exist.
 CMake Error at CMakeLists.txt:79 (configure_file):
   configure_file Problem configuring file


 CMake Error: File /root/ardronelib-build/ardronelib.pc.in does not exist.
 CMake Error at CMakeLists.txt:90 (configure_file):
   configure_file Problem configuring file


 -- Configuring incomplete, errors occurred!
```

Possible solutions could be fixing the README.md or modifying the CMakeList.txt to include pull orders from the repo.

**Comment by fqez** [comment]
Hi, you are right, the README.md is obsolete. The actual instructions can be found here: http://jderobot.org/Manual-5#Manual_installation_of_JdeRobot_.28for_the_brave.29
In the Sdk parrot subsection. I'll update the README.md ASAP,  sorry!

**Comment by lr-morales** [comment]
No problem.

**Comment by lr-morales** [comment]
Pull request #9 should help regarding this issue, @fqez.
